version: '3.5'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://fil:fil@localhost:5432/flask_test
      CONFIG_NAME: DevConfig
    volumes:
    - ./blog:/app/blog
    ports:
      - 5000:5000
    depends_on:
      - pg

  pg:
    image: postgres:12
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: fil
      POSTGRES_PASSWORD: fil
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ${HOME}/dbs/flask-lesson/pgdata_dev:/var/lib/postgresql/data/pgdata
    ports:
      - 8001:5432
