"""create is_staff for class User

Revision ID: 4bbab8913d93
Revises: bf6b7f020100
Create Date: 2021-07-09 19:17:53.781761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bbab8913d93'
down_revision = 'bf6b7f020100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('is_staff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'is_staff')
    # ### end Alembic commands ###
